### ISSUE TITLE
travis and install_zef_as_root.sh

### ISSUE THREAD

**Issue by gfldex** [nxadm/rakudo-pkg#10]
seams to setup a folder structure under ~/.zef whereby some subfolders are owned by root.

see https://github.com/gfldex/gfldex-meta-zef-test/blob/master/.travis.yml

As a workadound `sudo chown -R travis.travis /home/travis/.zef/` is making travis happy.

**Comment by nxadm** [comment]
Thx,

Isn't install_zef_as_user.sh an option for travis-like setups?

C.

**Comment by nxadm** [comment]
I am closing this. Feel free to reopen if you need a different solution.

C.
