### ISSUE TITLE
May we have a spin for Fedora 39?

### ISSUE THREAD

**Issue by ToddAndMargo** [nxadm/rakudo-pkg#100]
May we have a spin for Fedora 39, which hit two weeks ago.

**Comment by nxadm** [comment]
Hi @ToddAndMargo,

Fedora 39 was added to rakudo-pkg v2023.11.

**Comment by ToddAndMargo** [comment]
On 11/22/23 11:16, nxadm wrote:
> Hi @ToddAndMargo <https://github.com/ToddAndMargo>,
> 
> Fedora 39 was added to rakudo-pkg v2023.11.

Thank you!

 From my Get Updates program:

GetRaku  new update downloaded  0 --> 2023.11.01
