### ISSUE TITLE
2025.06 should be 2024.06

### ISSUE THREAD

**Issue by ToddAndMargo** [nxadm/rakudo-pkg#102]
https://github.com/nxadm/rakudo-pkg/releases/tag/v2025.06

https://github.com/nxadm/rakudo-pkg/releases/download/v2025.06/rakudo-pkg-Fedora39-2024.06-01.x86_64.rpm

https://github.com/nxadm/rakudo-pkg/releases/download/v2025.06/rakudo-pkg-Fedora40-2024.06-01.x86_64.rpm

Please change the tags from v2025.06 to v2024.06

**Comment by nxadm** [comment]
Tag deleted (and previously pushed the correct one). Thx!
