### ISSUE TITLE
May we have a 2017.04?

### ISSUE THREAD

**Issue by ToddAndMargo** [nxadm/rakudo-pkg#11]
Would you please compile RPM's up for 2017.04?

**Comment by nxadm** [comment]
Hi ToddAndMargo,

As you can see in the Release page, I originally created 2017.04 rpms (now marked as pre-release).

However, the upstream release had several problems and several dot releases were needed to fix them. The final working upstream release, however, is not the result of the *released* components (nqp, moarvm, rakudo) but is based on a emergency commit of nqp that has not been released.

I could try to add this one-off complexity to the build process, but I don't think it's worth it. It's only a few weeks to 2017.05.

C.

**Comment by ToddAndMargo** [comment]
Thank you.  I will wait for 2017.05!
