### ISSUE TITLE
install_zef_as_root name inconsistency? - RPM/DEB package has install_zef_as_root/install_zef_as_root.sh  - which is

### ISSUE THREAD

**Issue by melezhik** [nxadm/rakudo-pkg#14]
https://travis-ci.org/melezhik/sparrowdo/builds/287169789#L705-L735 - successful deb install 
https://travis-ci.org/melezhik/sparrowdo/builds/287169789#L4289-L4306 - - failed rpm install ( due to I expected the existence of install_zef_as_root.sh but it is install_zef_as_root )

**Comment by nxadm** [comment]
It looks that the discrepancy was fixed on more recent builds of the packages. 2017.09 doesn't have any references to the .sh variant. Can you bump the version or do you need an fixed 2017.07 package?

It is a leftover to the .sh -> 'no ext' transition in case I need to replace the shell script with one in an other language in the future.

C.

**Comment by melezhik** [comment]
Yeah, sure. If it's fixed in the recent versions it's enough. Thanks
