### ISSUE TITLE
Ubuntu 19.04 package

### ISSUE THREAD

**Issue by abraxxa** [nxadm/rakudo-pkg#47]
Please add a Ubuntu 19.04 package, thanks!

**Comment by nxadm** [comment]
Hi,

The server where the Rakudo releases were posted went down so the build scripts had no targets to download the sources. I hope the situation is restore when the new Rakudo is released (in a few days?). Once the download situation is clarified, I'll add support for Ubuntu 19.04 and Fedora 30 right away. If you need the package urgently, the one from 18.10 should work.

**Comment by abraxxa** [comment]
Yes, I saw that the failing Travis CI build was affected by the down server too. Thanks for the update!
As I've upgraded from 18.10 to 19.04 I still have it's package installed which works.

**Comment by abraxxa** [comment]
Any news on the package? Thanks!

**Comment by nxadm** [comment]
HI,

Still waiting on the upstream release. It should be out soon (I hope). More info on #perl6 channel on Freenode.

**Comment by nxadm** [comment]
I am now testing ubuntu 19.04, debian 10, fedora 30 and opensuse 15.1. I will probably release packages for 2019.03.1 because the new Rakudo release is not there yet.

**Comment by nxadm** [comment]
@abraxxa: New Ubuntu 19.04 pkg passes all test and is being build and uploaded by travis as we speak. Thanks for the follow up.

**Comment by abraxxa** [comment]
Yesterday they wheren't available but today, thanks!
