### ISSUE TITLE
Possible error in Documentation

### ISSUE THREAD

**Issue by borisdaeppen** [nxadm/rakudo-pkg#57]
In the documentation it says:

    Alternatively, a script is supplied to do this automatically for you. Run it as your regular user:
    
        $ /opt/rakudo-pkg/bin/add-raku-to-path

But on my system I only find add-raku**do**-to-path:

    $ ls /opt/rakudo-pkg/bin/ | grep raku
    add-rakudo-to-path
    raku
    rakudo

This after following the download instructions for the OS Repositories (via apt).

Is it that the documentation is newer than the software-package which its describing?
Something is not right here... but I'm not sure

I'm trying to try Raku the first time, and I'm already stumbling here :-)
Maybe we can fix this asap?

Ps: Great page!

**Comment by nxadm** [comment]
Good catch. It's related to the renaming of perl6 to raku. I'll fix it now.

**Comment by nxadm** [comment]
Fixed by https://github.com/nxadm/rakudo-pkg/commit/0ec62f9bdc4ad415a173025eb6d8380048fb4ebf
