### ISSUE TITLE
install-zef-as-user final note is no longer valid

### ISSUE THREAD

**Issue by Scimon** [nxadm/rakudo-pkg#62]
```
1 bin/ script [zef] installed to:
/home/sproctor/.raku/bin
Don't forget to add '~/.perl6/bin' to your PATH,
e.g. by adding this to .profile:
export PATH=~/.perl6/bin:PATH
```
This also mean anyone who did update their `PATH` needs to do it again.

**Comment by nxadm** [comment]
Thx @Scimon,

I will fix the instructions for the upcoming pkg. I'll keep this open in the meanwhile.

**Comment by nxadm** [comment]
Fixed on the upcoming package revision. Thx!
