### ISSUE TITLE
Debian dependency missing on Stretch (Debian 9, hard-to-read link

### ISSUE THREAD

**Issue by tbrowder** [nxadm/rakudo-pkg#63]
Great packaging, @nxadm, thanks!

But I can report couple of nits I had on Debian stretch (9):

0. The first problem I had was reading the link: "dl" looked like "d1" in one browser view. A copy/paste would have worked, but I didn't have that available for the first server. A rename of the server would be ideal but probably not feasible.

1. On a stretch box using the lsb line (the second of the three lines in the instructions) I had trouble until I found a missing dependency on the package: apt-transport-https.

**Comment by nxadm** [comment]
thx @tbrowder,

I'll update the docs where necessary!

**Comment by tbrowder** [comment]
Thanks for all your work--it really helps keep up with the latest and helps me help to introduce Raku to other Linux users.

**Comment by nxadm** [comment]
The instructions to install a repo were changed to adapt them to the migration to CloudSmith (now in branch nfpm). Running tests now.
