### ISSUE TITLE
Linux Mint 19.3 (Tricia) Support

### ISSUE THREAD

**Issue by evenwilder** [nxadm/rakudo-pkg#66]
Hello, 

I attempted to install rakudo on Linux Mint 19.3 (Tricia) but was unsuccessful. After some troubleshooting I noticed that the directory tricia/ is missing from https://dl.bintray.com/nxadm/rakudo-pkg-debs/dists/. Will you please update your repository such that Linux Mint 19.3 is supported?

Thanks!

**Comment by nxadm** [comment]
Will certainly do. What ubuntu base does Minit 19.3 use? 18.04?

Adding support for Mint releases is as simple as adding them in the Ubuntu line, e.g.:
https://github.com/nxadm/rakudo-pkg/blob/master/.travis.yml#L28

What will be the Mint version using Ubuntu 20.04? Feel free to feed me Mint info to we can keep the repos up to date for the distro as well.

Thx!

**Comment by evenwilder** [comment]
Hello,

Linux Mint 19.3 (Tricia) uses Ubuntu 18.04 (Bionic Beaver) as its base. I
believe Linux Mint 20 will be based upon Ubuntu 20.04.

Thanks!

**Comment by nxadm** [comment]
Added to the upcoming revision (today).
