### ISSUE TITLE
no candidate found for 'zef' that match your criteria

### ISSUE THREAD

**Issue by kanliot** [nxadm/rakudo-pkg#67]
I installed through the main page https://nxadm.github.io/rakudo-pkg/
adding the deb repository to /etc/apt/sources.list.d/rakudo-pkg.list and then installing rakudo-pkg

I fixed my paths, but didn't reboot.  zef isn't working as seen below.    Not sure what I did wrong.

    kanliot@maleday:/opt/rakudo-pkg/bin$ zef --help
    ===SORRY!===
    No candidate found for 'zef' that match your criteria.
    Did you perhaps mean one of these?
      Author(ity) | Distribution | Version
                  |              |        
                  |              |        
                  |              |        
                  |              |

**Comment by nxadm** [comment]
Hi,

`kanliot@maleday:/opt/rakudo-pkg/bin$ zef --help` lookes for zef in the $PATH.

If you want to use the root zef (probably not what you want):
`/opt/rakudo-pkg/bin/zef --help`

If you want to use the zef in your $HOME, `~/.perl6/bin` shoud be in your PATH, I suppose it isn't:
can you do the command below and verify the directory is there?
```sh echo $PATH``'

If not, you need to add it the .profile (or an other shell init), e.g.:
 ```sh
PATH=~/.perl6/bin:/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH
export PATH
```

**Comment by kanliot** [comment]
sh -c 'echo $PATH'   #returns normally 

    PATH=~/.perl6/bin:/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH
    export PATH

Yeah. above fixes it.  Not sure what I did wrong, but thank you.  I'm 99% sure it was my error. 

also there's this line in my `~/.profile`:    
    `PATH=~/.perl6/bin:.:/opt/rakudo-pkg/share/perl6/site/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

why did `.` get added to the path?   I think it was `/opt/rakudo-pkg/bin/add-rakudo-to-path`  that added `.`. 

If you like I can create a separate "issue" for the `.` problem. 

Thank you kindly for your help nxadm.

**Comment by nxadm** [comment]
No problem, feel free to open issues.
