### ISSUE TITLE
Alpine repositories

### ISSUE THREAD

**Issue by melezhik** [nxadm/rakudo-pkg#68]
> There is no Alpine repo at the moment. 

Hi! Any plans for that?

Now I have to reference to a certain apk version URL and change it every time new version arrives. 

https://github.com/melezhik/sparrowdo/blob/master/resources/bootstrap.sh#L8

**Comment by nxadm** [comment]
The problem is that Jfrog, that holds the rpm and deb repos don't support APK repos yet. APK should be hosted elsewhere.

**Comment by melezhik** [comment]
I see.

**Comment by melezhik** [comment]
No rush. Just a thought. Thanks for clarification.

**Comment by nxadm** [comment]
Good news. Working on this. I will add it after push the refactoring of rakudo-pkg built around Github Actions.

**Comment by nxadm** [comment]
The new repos already work, now running some tests to make sure everything is OK.
