### ISSUE TITLE
Fedora 32

### ISSUE THREAD

**Issue by ToddAndMargo** [nxadm/rakudo-pkg#69]
May we please have a spin for Fedora 32?

**Comment by nxadm** [comment]
I am working on a new build infra for rakudo-pkg and the funny coincidence is that I worked on the Fedora 32 image since I saw it's on Dockerhub. I'll add it soon (depending on time).

**Comment by ToddAndMargo** [comment]
On 2020-04-28 13:20, nxadm wrote:
> I am working on a new build infra for rakudo-pkg and the funny 
> coincidence is that I worked on the Fedora 32 image since I saw it's on 
> Dockerhub. I'll add it soon (depending on time).

cool!

**Comment by nxadm** [comment]
Doing a test build on travis as we speak (also bumped zef for all the distros). If no surprises, we're a tag away from Fedora 32 packages.

**Comment by nxadm** [comment]
The Fedora 32 repo has a newpackage now, but I am releasing new packages for all distros with an updated zef. They are being build now on travis. I will check them and promote them to the latest release after I wake up :)
