### ISSUE TITLE
Debian Buster (Debian 10): missing dependencies 

### ISSUE THREAD

**Issue by tbrowder** [nxadm/rakudo-pkg#70]
A clean installation of Debian Buster needed the following additional packages to be installed in order to install `rakudo-pkg`:

+ `apt-transport-https`
+ `dirmngr`
+ `lsb-release`

**Comment by nxadm** [comment]
The instructions to install a repo were changed to adapt them to the migration to CloudSmith (now in branch nfpm). Running tests now.
