### ISSUE TITLE
Bintray going down

### ISSUE THREAD

**Issue by Altai-man** [nxadm/rakudo-pkg#74]
Hi. I am not sure how is that used, but there is e.g. https://dl.bintray.com/nxadm/rakudo-pkg-debs/ showing in my browser history.

If we use it to ship something, there are news about it going down in May, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Sorry for the noise and can be closed if irrelevant to us.

**Comment by nxadm** [comment]
Thx, for the headsup @Altai-man. Weird enough I commenced to evaluate Cloudsmith with the idea to offer Alpine repo's. I guess I'll host debs and rpms there as well if it works OK.

**Comment by nxadm** [comment]
Move in progress to CloudSmith. Thx!
