### ISSUE TITLE
raku not found under Wayland

### ISSUE THREAD

**Issue by abraxxa** [nxadm/rakudo-pkg#83]
Because `/etc/profile` and by that `/etc/profile.d/rakudo-pkg.sh` isn't sourced when running Wayland.
Setting env vars is the biggest mess on Linux for me as there are not only differences by dists but now also between X11 and Wayland.
There is /etc/environment.d which might be a good place (for Ubuntu? Not sure about Debian and other Distros).
Systemd has it's way of doing things too.

**Comment by nxadm** [comment]
TBD indeed.

**Comment by nxadm** [comment]
We can't do much about Wayland, but a script is installed to add raku your $HOME/.profile:
https://github.com/nxadm/rakudo-pkg/blob/master/include/add-rakudo-to-path

I think this suffices. Reopen if you think it does not.

**Comment by abraxxa** [comment]
Are there any docs that point to it?
As it's in the same directory as raku itself, it isn't in the path either.
When installing a distro specific package, I expect that it handles distro specific things like setting up it's usability.

**Comment by nxadm** [comment]
The doc is here, linked from the README.md: https://github.com/nxadm/rakudo-pkg/blob/master/docs/path.md

**Comment by abraxxa** [comment]
I've only found https://unix.stackexchange.com/questions/578046/setting-path-on-wayland-gnome but no docs on how a wayland session wide env var can be set.
