### ISSUE TITLE
automated setup with derivative OS

### ISSUE THREAD

**Issue by finanalyst** [nxadm/rakudo-pkg#86]
I had to do forget about Raku for about a year due to other $tuff. Came back and wanted to update to new Raku with your packages. In meantime, I upgraded my OS, which is Pop OS from System76. Its based on Ubuntu.
Your setup script worked well. But ... 
In the package list files, eg., "/etc/apt/sources.list.d/nxadm-pkgs-rakudo-pkg.list"
The OS is given as 'pop', viz., "deb ... /deb/pop xxx main". The 'pop' needs to be changed to 'ubuntu'.
You refer to this problem on the cloudsmith site.

I suggest you add a trouble-shooting example, eg., 
"If you use an OS derivative, eg., Pop OS, which is based on the Ubuntu distribution, and the automatic Setup script given above finishes, but rakudo-pkg is not recognised after running 'apt info rakudo-pkg', then look at '/etc/apt/sources.list.d/nxadm-pkgs-rakudo-pkg.list' and see whether there is a reference to 'pop'. If so, replace 'pop' with 'ubuntu' or the equivalent(s) for your derivative OS. Rerun 'apt update'."

It took me a while to remember all this today, and an example might have made it easier.

In any case, thank you for all your work to make this distribution available.

**Comment by nxadm** [comment]
Hi @finanalyst,

The cloudsmith instructions are autogenerated by them, so there isn't much I can change there. Maybe your usecase is handled by these instructions (that we should document somewhere):

> If you need to force a specific distribution, release/version, or even architecture, you can also do that (e.g. if your system is compatible but not identical): 

```bash
curl -1sLf \
  'https://dl.cloudsmith.io/public/nxadm-pkgs/rakudo-pkg/setup.deb.sh' \
  | sudo -E distro=some-distro codename=some-codename arch=some-arch bash

```
