### ISSUE TITLE
OpenSuse rakudo-pkg 2021.12.0-01 versions

### ISSUE THREAD

**Issue by bazzaar** [nxadm/rakudo-pkg#87]
Hi. I'm just wondering why the OpenSuse rakudo-pkg 2021.12.0-01 versions aren't available (all the rest seemed to get built a few days ago). I've been using the rakudo-pkg repo to update my raku install (via Yast) for the last few years and it's been an excellent resource, thanks so much for providing this service. (I used to install Rakudo Star prior to this, and that was quite a bit more hit and miss.) I'm still on Leap 15.2, so that's the rakudo-pkg I'm specifically looking for.

**Comment by nxadm** [comment]
Hi @bazzaar ,

In order not to keep increasing the number of builds (we run now 22 os+versions), I remove distributions once they reach EOL. 

According to https://endoflife.date/opensuse, which I consulted at the package creation time, 15.2 reached end-of-life on 2021/12/01. According to the more official https://en.opensuse.org/Lifetime, which I should have checked although more difficult to parse :), 15.2 was EOL on 2021/12/31.

**Comment by bazzaar** [comment]
Thanks for your reply, @nxadm.

I hadn't realised that the Leap15.2 reached EOL (for OpenSuse maintainance and support) at the end of 2021. I do understand the need to keep a lid on the number of OS versions. 

Then again, from my perspective it does feel a little like the tail wagging the dog. Rakudo is but one component (true it uses other system components), whereas the OS caters for thousands of components. I'm currently having to maintain 4 installations spread about the country (mine, and grand-kids) and in these Covid times, access to the machines is limited. Even though they are all now running with fully updated system packages (as of the last month or so), the application (Raku) that is the primary creative object, is now politely saying upgrade your OS, post the OpenSuse EOL.

**Comment by nxadm** [comment]
I don't mind re-adding it to the builds for e.g. 6 months to help you out. 

(However, rakudo-pkg is actually doing the same as openSUSE does: they did cease all the updates already. I am pretty sure, you are aware of the security implication that will grow over time when no OS updates are applied.)

**Comment by bazzaar** [comment]
@nxadm, that would be much appreciated at this time. I do agree there has to be a cut-off date (6 months would seem a good choice), and maybe there has to be a proviso given (use at own peril, for example) after OS Official EOL.

However, if it turns out to be more complicated, on reflection, then I'm 100% happy with whatever you decide to do on this.

**Comment by nxadm** [comment]
Hi @bazzaar,

The package was uploaded to the repo.
