### ISSUE TITLE
WIP: Suggestions for Debian doc changes for the current system

### ISSUE THREAD

**Issue by tbrowder** [nxadm/rakudo-pkg#89]
First, when copying the recommended curl script using the copy button, I get two right-angle brackets on my system that are not shown on your instructions. But they were necessary for it to work. (On another clean attempt, I first executed "sudo su" before I attempted the default method and all worked cleanly with on additional intervention on my part.)

Second, it may be helpful to remind readers the scripts must be run as the root user.

I may detail them later with a PR, but following are some other doc suggestions for users of your older systems:

+ I would add to the section on deleting the rakudo-pkg system deleting any old 'rakudo-pkg.sh' file in '/etc/profile.d'.
+ It may be worthwhile mentioning the new paths and '/etc/apt/sources.list.d list' file name versus the original (old 'rakudo-pkg.list' vs the new 'nxadm-pkgs-rakudo-pkg.list') to let older users know they need to totally update to the new system.

**FINALLY** I would like to see a separate zef install script that would install all packages, including zef, to the /opt/rakudo-pkg directory in an appropriate place when the root user installs or upgrades any package. That would enable sysadmins of small systems to hold down disk usage and he or she could help new Raku users use modules before having to learn the currently painful use of zef and its **MANY** and confusing options.

Thanks to @ugexe's explantion on IRC, such a thing can be accomplished by the user root running:

    # zef install --install-to=site Some::Module

Then, for ordinary users using the same Raku as root (which should normally be the case for a rakudo-pkg installation), that same module will be "use"able automatically. The user can always install or upgrade modules on his his own, but for casual or new Raku users, installation by root can reduce complexity as well as save space on small hosts.

**Comment by nxadm** [comment]
thx @tbrowder,

> First, when copying the recommended curl script using the copy button, I get two right-angle brackets on my system that are not shown on your instructions. But they were necessary for it to work. (On another clean attempt, I first executed "sudo su" before I attempted the default method and all worked cleanly with on additional intervention on my part.)
> 
> Second, it may be helpful to remind readers the scripts must be run as the root user.

Instructions seem to work for me, but if we can make them better we should send a PR to Cloudsmith.

> I may detail them later with a PR, but following are some other doc suggestions for users of your older systems:
> 
>     * I would add to the section on deleting the rakudo-pkg system deleting any old 'rakudo-pkg.sh' file in '/etc/profile.d'.

We moved quite a while to the new repos. I wouldn't confuse new users with the old setup.


>     * It may be worthwhile mentioning the new paths and '/etc/apt/sources.list.d list' file name versus the original (old 'rakudo-pkg.list' vs the new 'nxadm-pkgs-rakudo-pkg.list') to let older users know they need to totally update to the new system.

Added to the main README.md.

> 
> **FINALLY** I would like to see a separate zef install script that would install all packages, including zef, to the /opt/rakudo-pkg directory in an appropriate place when the root user installs or upgrades any package. That would enable sysadmins of small systems to hold down disk usage and he or she could help new Raku users use modules before having to learn the currently painful use of zef and its **MANY** and confusing options.
> 
> Thanks to @ugexe's explantion on IRC, such a thing can be accomplished by the user root running:
> 
> ```
> # zef install --install-to=site Some::Module
> ```
> 
> Then, for ordinary users using the same Raku as root (which should normally be the case for a rakudo-pkg installation), that same module will be "use"able automatically. The user can always install or upgrade modules on his his own, but for casual or new Raku users, installation by root can reduce complexity as well as save space on small hosts.

I added /opt/rakudo-pkg/bin/zef-as-root for that purpose. Does this work for you?

Reopen the issue if you need additional changes.
