### ISSUE TITLE
Repository / package for Leap 15.4

### ISSUE THREAD

**Issue by bazzaar** [nxadm/rakudo-pkg#90]
Edit: It might be there is no package yet available for Leap 15.4

..... Original issue text .....
I've finally got around to upgrading from Opensuse Leap 15.2. Have skipped an OS version and gone straight to the new Leap 15.4.

However, I'm having trouble setting up the Repository for rakudo package, following the instructions for the OS variant.

Getting an "Could not fetch repository config!" error. My problem is I don't know what to put in the : 

distro=  
version=
codename=
arch=

it doesn't seem to be the same scheme as 15.2, as with that I'm still able to fetch the config.sh

**Comment by nxadm** [comment]
I added support for 15.4 on the new rakudo release (should be out today).

**Comment by bazzaar** [comment]
Thanks nxadm for adding the Leap 15.4 rakudo pkg, I was sure you would address the issue ( and thinking probably at the next rakudo release, which I thought might be 2022.08), so to see it appear at the start of August is a bonus, and perfect timing for me :+1:

I can confirm the set repo instructions for OpenSuse Leap 15.4, and the install of the rakudo package via YAST worked well, and that Raku seems to be functioning correctly for me.

The script to add raku to my Path worked, however I encountered an issue using the command to set-up zef which is detailed in the rakudo_pkg Readme. So I'll maybe open up a new issue for that.
