### ISSUE TITLE
site path - share/perl6/bin vs share/perl6/site/bin

### ISSUE THREAD

**Issue by jaguart** [nxadm/rakudo-pkg#94]
My dist - Debian 11.5. I'm aiming to get my hosts set up with a site-wide rakudo and zef.

Installation adds ``/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/bin`` into the path via profile.d inclusion.

I wonder if the second part should be ``/opt/rakudo-pkg/share/perl6/site/bin`` - this is where site-wide bin files are added by zef running without any options, according to my tests.

**Comment by nxadm** [comment]
You are correct, @jaguart. The paths of the zef installation changed along the road, so I changed it (add add the new lib path to zef-as-root):
https://github.com/nxadm/rakudo-pkg/compare/master...miscFixes

It will be merged soon with other fixes.
